# Generated by Django 5.0 on 2024-01-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_author_remove_article_author_alter_article_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articles',
            new_name='authors',
        ),
    ]
