# Generated by Django 5.0 on 2024-01-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(db_index=True, verbose_name='date published'),
        ),
    ]
