# Generated by Django 5.0 on 2024-01-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price_alter_product_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='UserToProduct',
        ),
    ]
