# Generated by Django 5.0 on 2024-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_orderentry_profile_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN', 'Initial'), ('CP', 'Completed'), ('DL', 'Delivered')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
